# Generated by Django 4.0.3 on 2022-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_description_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотографія', 'verbose_name_plural': 'Фотографії'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Короткий опис / назва'),
        ),
    ]
